import React, { createContext, useState } from 'react';

export const FacultyInfoContext = createContext();

export const FacultyInfoProvider = ({ children }) => {
  const [classInfo, setClassInfo] = useState([
    {
        class_id:1,
        class_faculty: [6011, 6012],
        class_name: "数学の基礎A-1",
        class_overview: "この講義では高度な知識や計算能力に偏ることを避け，大学入学以前の数学カリキュラムの中から，都市や情報を科学的に取り扱う上で必要不可欠な部分を中心に，数学とコンピュータとの結びつきに触れつつ講義を行う。",
        class_teacher: "宇野　隆",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610167&value(crclumcd)=07181",
        class_connection_job: [11, 6, 1],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 1,
        class_time: 1,
        class_review: ["課題はない", "毎週小テストがあるのでプリントの問題をできるようにする", "スライドに書かれていることをノートに写す時間があるのでそこで絶対に写す。(テスト勉強に使う)", "定期テストは2回あり、プリントとノートを使って勉強をすれば点数はとれる。", "だいたい10分から15分前には講義がおわる。"]
      },
      {
        class_id:2,
        class_faculty: [6011, 6012],
        class_name: "ジェンダーと社会",
        class_overview: "現代社会におけるジェンダーに関する基礎知識を学び、ジェンダーの視点で私たちの就職、結婚、出産、子育て等のライフサイクルについて学習する。",
        class_teacher: "竹内　愛",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610015&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 1,
        class_time: 2,
        class_review: ["毎週講義後のまとめとして200字程度webクラスに提出"]
      },
      {
        class_id:3,
        class_faculty: [6011, 6012],
        class_name: "人間と社会の演習",
        class_overview: "健康と病、社会生活、社会情報の観点から人間と社会について研究し、人間の本質を理解することが目的である。",
        class_teacher: "酒井　順哉",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610016&value(crclumcd)=07181",
        class_connection_job: [11],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 1,
        class_time: 2,
        class_review: ["課題は毎週5問の小テストと200字レポートが2つある。", "予習課題はない", "定期テストは資料を持ち込みできるので毎週印刷しておく", "資料さえあればテストは大丈夫(資料の量が多く探すのに時間がかかるのでどこに何がかかれているのかを把握しておく)", "講義中にテストに出るところを教えてくれる時があるので聞いておくこと。"]
      },{
        class_id:4,
        class_faculty: [6011, 6012],
        class_name: "都市と文化",
        class_overview: "都市史や都市論について概観したあと，まちづくりや文化の視点から都市の特徴や課題について捉えていく。",
        class_teacher: "小川　知弘",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610171&value(crclumcd)=07181",
        class_connection_job: [11, 2],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 1,
        class_time: 3,
        class_review: ["一回簡単なレポートがある。", "定期テストは持ち込みなしで、けっこう難しい", "言葉の意味を自分で説明できるようにしておくこと。"]
      },
      {
        class_id:5,
        class_faculty: [6011, 6012],
        class_name: "健康・スポーツ科学1(バドミントン)",
        class_overview: "まず自身の体力レベルを理解し、その改善点について各自で検討する。また、バドミントンの実施を通して技術と体力の向上を図るほか、他者とのコミュニケーション能力の向上に努める。",
        class_teacher: "冨岡　徹",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610081&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 1,
        class_time: 3,
        class_review: ["毎週感想を100文字程度その日中にWEBクラスで提出", "先生が優しく、指導が上手", "10回までは練習多めでそれ以降はダブルスの総当たり", "めっちゃ楽しい！！からだをうごかせる"]
      },
      {
        class_id:6,
        class_faculty: [6011, 6012],
        class_name: "健康・スポーツ科学1(フットサル)",
        class_overview: "まず自身の体力レベルを理解し、その改善点について各自で検討する。また、フットサルの実施を通して技術と体力の向上を図るほか、他者とのコミュニケーション能力の向上に努める。",
        class_teacher: "千葉　洋平",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610082&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 1,
        class_time: 3,
        class_review: [],
      },
      {
        class_id:7,
        class_faculty: [6011, 6012],
        class_name: "健康・スポーツ科学1(バドミントン)",
        class_overview: "まず自身の体力レベルを理解し、その改善点について各自で検討する。また、バドミントンの実施を通して技術と体力の向上を図るほか、他者とのコミュニケーション能力の向上に努める。",
        class_teacher: "冨岡　徹",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610083&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 1,
        class_time: 4,
        class_review: ["毎週感想を100文字程度その日中にWEBクラスで提出", "先生が優しく、指導が上手", "10回までは練習多めでそれ以降はダブルスの総当たり", "めっちゃ楽しい！！からだをうごかせる"]
      },{
        class_id:8,
        class_faculty: [6011, 6012],
        class_name: "健康・スポーツ科学1(フットサル)",
        class_overview: "まず自身の体力レベルを理解し、その改善点について各自で検討する。また、フットサルの実施を通して技術と体力の向上を図るほか、他者とのコミュニケーション能力の向上に努める。",
        class_teacher: "千葉　洋平",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610084&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 1,
        class_time: 4,
        class_review: []
      },
      {
        class_id:9,
        class_faculty: [6011, 6012],
        class_name: "フランス語入門1",
        class_overview: "平易なフランス語の文や表現とそれらを理解するために必要な初級文法を，毎回少しずつ学ぶ。",
        class_teacher: "山口　憲男",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610064&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 1,
        class_review: ["課題なし", "教科書は絶対いるので買った方がいい", "講義中にホワイトボードにかかれたことは絶対ノートに写す", "定期テストにはノートと教科書を持ち込める", "講義をしっかり受けていないとわからなくなる"]
      },{
        class_id:10,
        class_faculty: [6011, 6012],
        class_name: "ドイツ語入門1",
        class_overview: "ドイツ語の文法・読解力の基礎を身につけるために、ドイツ語の文を繰り返し音読したり、練習問題を解いたり、復習の小テストをしたりする。",
        class_teacher: "木股　錬治",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=211137&value(crclumcd)=02112",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 1,
        class_review: ["リーディング、ライティングがメイン"]
      },
      {
        class_id:11,
        class_faculty: [6011, 6012],
        class_name: "健康・スポーツ科学1(バレーボール)",
        class_overview: "まず自身の体力レベルを理解し、その改善点について各自で検討する。また、健康・スポーツ科学Ⅰ（バレーボール）の実施を通じて技術と体力の向上を図るほか、他者とのコミュニケーション能力の向上に努める。",
        class_teacher: "黒田　真二",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610085&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 1,
        class_review: ["課題は毎週感想を100字webクラスで提出。", "最後に一個体育測定のレポートがある", "先生が面白く優しい", "経験者も少しはいるが無経験の人が多い", "チームはその日その日で勝手に決められる"]
      },
      {
        class_id:12,
        class_faculty: [6011, 6012],
        class_name: "健康・スポーツ科学1(バスケットボール)",
        class_overview: "まず自身の体力レベルを理解し、その改善点について各自で検討する。また、健康・スポーツ科学Ⅰ（バスケットボール）の実施を通じて技術と体力の向上を図るほか、他者とのコミュニケーション能力の向上に努める。",
        class_teacher: "黒田　真二",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610086&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 2,
        class_review: []
      },{
        class_id:13,
        class_faculty: [6011, 6012],
        class_name: "フランス語初級1",
        class_overview: "基礎的なフランス語文法の後半を学ぶ。新たな語学の習得のためには最低限の文法を学ぶことが必要不可欠である。また、外国語を学ぶことによりコミュニケーション能力を一層高め、他言語文化に目を向けることを目的としている。",
        class_teacher: "山口　憲男",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=211533&value(crclumcd)=02112",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 2,
        class_review: ["課題なし", "教科書は絶対いるので買った方がいい", "講義中にホワイトボードにかかれたことは絶対ノートに写す", "定期テストにはノートと教科書を持ち込める", "講義をしっかり受けていないとわからなくなる(入門より少し難しい)"]
      },
      {
        class_id:14,
        class_faculty: [6011, 6012],
        class_name: "ドイツ語初級1",
        class_overview: "ドイツ語の文法・読解力の基礎を身につけるために、文法の説明のみならず、音声も重視して、ドイツ語の文を繰り返し音読したり、練習問題を解いたり、復習の小テストを行う。",
        class_teacher: "木股　錬治",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=211534&value(crclumcd)=02112",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 2,
        class_review: ["スピーキングがメイン"]
      },
      {
        class_id:15,
        class_faculty: [6011, 6012],
        class_name: "経済と社会",
        class_overview: "現代社会における経済現象は様々な要因によって影響を受けます。この講義では、その複雑な経済現象を把握するのに必要な基礎的知識を理解し、経済学の考え方を習得する。",
        class_teacher: "赤木　博文",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610173&value(crclumcd)=07181",
        class_connection_job: [6, 7, 11],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 2,
        class_review: ["課題なし", "小テスト一回", "定期テストは持ち込みができる"]
      },{
        class_id:16,
        class_faculty: [6011, 6012],
        class_name: "健康・スポーツ科学1(バドミントン)",
        class_overview: "まず自身の体力レベルを理解し、その改善点について各自で検討する。また、健康・スポーツ科学Ⅰ（バドミントン）の実施を通じて技術と体力の向上を図るほか、他者とのコミュニケーション能力の向上に努める。",
        class_teacher: "黒田　真二",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610087&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 3,
        class_review: ["毎週感想を100文字程度その日中にWEBクラスで提出", "先生が優しく、指導が上手", "10回までは練習多めでそれ以降はダブルスの総当たり", "めっちゃ楽しい！！からだをうごかせる"]
      },
      {
        class_id:17,
        class_faculty: [6011, 6012],
        class_name: "健康・スポーツ科学1(卓球)",
        class_overview: "スポーツ種目（卓球）の実施を通して技術と体力の向上を図るほか、他者とのコミュニケーション能力の向上に努める。",
        class_teacher: "武山　祐樹",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610088&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 3,
        class_review: ["課題は毎週講義の感想を100字書いてwebクラスに提出。", "初めの方は練習が多め", "途中からチームを組んで団体戦を行う", "1年生だけではなく2.3年生の人もいる"]
      },
      {
        class_id:18,
        class_faculty: [6011, 6012],
        class_name: "都市学英語1",
        class_overview: "本講義は、日本語より論理的と言われる英文を使って文章の論理的構成を勉強する。様々な分野の記事を読み、パラグラフ・リーディングの訓練を行う。",
        class_teacher: "鎌田　繁則",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611105&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 3,
        class_review: ["課題は次の講義でやるページを予習(長文和訳と問題)", "毎講義だいたい一回予習の長文和訳か問題で当てられる。", "定期テストはどこの長文がでるのか教えてくれるのでそこの和訳と問題を完璧にしておけばいける。簡単", "テキストは絶対必要"]
      },{
        class_id:19,
        class_faculty: [6011, 6012],
        class_name: "都市学英語1",
        class_overview: "新聞および専門分野に関する文献を英語で読むことにより，実際に使われる英語を身につける．",
        class_teacher: "鈴木　敦生",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611107&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 3,
        class_review: []
      },
      {
        class_id:20,
        class_faculty: [6011, 6012],
        class_name: "都市学英語1",
        class_overview: "都市学の専門英語を学び、英語により都市学を理解できる素養を身に付ける。",
        class_teacher: "昇　秀樹",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611108&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 3,
        class_review: []
      },
      {
        class_id:21,
        class_faculty: [6011, 6012],
        class_name: "都市学英語1",
        class_overview: "ビジネス英語、時事英語、経済・経営系の英文文献を材料として、ビジネスニュース等の英文を和訳しながら、英語力を鍛えると同時にビジネス、経済・経営学全般の理解を深める",
        class_teacher: "雑賀　憲彦",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=612114&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 3,
        class_review: ["自己PRの添削をしてくれる。", "就職に関して情報を与えてくれる。", "都市学英語の中で多分一番難しい"]
      },{
        class_id:22,
        class_faculty: [6011, 6012],
        class_name: "都市学英語1",
        class_overview: "都市論、 都市計画に関する英語文献を講読することで、 専門英語の読解力と当該専門分野における基礎的な知識や考え方を身に付ける。 また、 英語文献を素材としたまちづくり演習など、 参加型・演習型の授業を通じてより実践的な英語に触れさせる。",
        class_teacher: "福島　茂",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611109&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 1,
        class_time: 3,
        class_review: []
      },
      {
        class_id:23,
        class_faculty: [6011, 6012],
        class_name: "都市学英語1",
        class_overview: "アメリカの都市における人々の暮らしと都市を取り巻く地域社会の実情や地理的・歴史的・文化的・社会経済的背景について英文を用いて学びながら、それぞれの都市の抱える課題を取り上げて検討していく",
        class_teacher: "手嶋　正章",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611106&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 3,
        class_review: []
      },
      {
        class_id:24,
        class_faculty: [6011, 6012],
        class_name: "都市学英語1",
        class_overview: "様々な都市問題のうちで、特に環境問題および公害問題について英文で学習する",
        class_teacher: "赤木　博文",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611110&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 4,
        class_review: []
      },{
        class_id:25,
        class_faculty: [6011, 6012],
        class_name: "都市学英語1",
        class_overview: "海外の都市の発展を理解するため、毎年世界の主要都市問題に関する外国文献を選び、外国の都市の実情を理解するために必要な英語の読解力を要請する",
        class_teacher: "稲葉　千晴",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611111&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 4,
        class_review: ["ウクライナの話が聞ける。", "定期テストがない", "スピーキングテストがある。"]
      },
      {
        class_id:26,
        class_faculty: [6011, 6012],
        class_name: "都市学英語1",
        class_overview: "現代社会および日本地誌に関連する英文を通して，日本の社会的経済的特徴に関する理解を深める。",
        class_teacher: "杉浦　真一郎",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611112&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 4,
        class_review: []
      },
      {
        class_id:27,
        class_faculty: [6011, 6012],
        class_name: "都市学英語1",
        class_overview: "科学英文に関する技法を，学ぶとともに和文と英文の構造上の違いを理解し， 英文技法を学ぶ．",
        class_teacher: "若林　拓",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611113&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 4,
        class_review: []
      },{
        class_id:28,
        class_faculty: [6011, 6012],
        class_name: "健康・スポーツ科学1(卓球)",
        class_overview: "スポーツ種目（卓球）の実施を通して技術と体力の向上を図るほか、他者とのコミュニケーション能力の向上に努める。",
        class_teacher: "武山　祐樹",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610088&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 4,
        class_review: ["課題は毎週講義の感想を100字書いてwebクラスに提出。", "初めの方は練習が多め", "途中からチームを組んで団体戦を行う", "1年生だけではなく2.3年生の人もいる"]
      },
      {
        class_id:29,
        class_faculty: [6011, 6012],
        class_name: "国際化時代の人間と社会",
        class_overview: "国際的な人権の問題に言及する。20世紀最大の悲劇であるユダヤ人大量虐殺「ホロコースト」および「ホロコースト」の危機にあるユダヤ人を救った「有徳の人」にスポットを当てる。",
        class_teacher: "稲葉　千晴",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610012&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 5,
        class_review: ["パワーポイントで偉人のテキストから一人選びその人についての発表資料を作る。（発表はしない）"]
      },
      {
        class_id:30,
        class_faculty: [6011, 6012],
        class_name: "情報社会と倫理",
        class_overview: "始めに情報技術の進展が社会に及ぼす影響について技術の面から概観する。次に、我々が情報の利用及び発信に際して、必要とされる知識や行為について社会学や倫理学の観点から考察を行い、法律との関連について学ぶ。",
        class_teacher: "御幸　英寛",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610079&value(crclumcd)=07181",
        class_connection_job: [1, 3, 7, 11],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 2,
        class_time: 5,
        class_review: ["課題は毎週レポートがある。選ばれると点数が高くなる。"]
      },{
        class_id:31,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1(リーディング)",
        class_overview: "語彙を増やす・速読をする・読解活動をグループで行った後に討論をしてReadingを通じて理解した内容をDiscussion/Speakingしてクラスメイトと理解を深める。",
        class_teacher: "高野　洋子",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611020&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 1,
        class_review: ["単語の意味とその単語を使った文章を作る課題がでる。", "簡単な英語の本を読む課題もでる。", "定期テストは言われたところを勉強すれば簡単に点がとれる", "1.2回グループで簡単なプレゼンテーションをする。"]
      },
      {
        class_id:32,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1(コミュニケーション)",
        class_overview: "今や国際語となっている英語については、「読む・書く・聴く・話す」の４技能について各自の能力に応じた効果的な学習によりそのスキルの向上を図るとともに、外国の文化や社会に対する認識を深めることを目標とする。",
        class_teacher: "テレサ　カネンバーグ",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611025&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 1,
        class_review: ["課題は、英語で自分の自己紹介をするレポートや英語で好きな場所を紹介するレポートがたまにでる", "講義はテキストを使って行われる", "定期テストは持ち込みなしだが言われたところを少し勉強しておけば大丈夫"]
      },
      {
        class_id:33,
        class_faculty: [6011, 6012],
        class_name: "英語初級1-1(コミュニケーション)",
        class_overview: "語学力の目的はコミュニケーションです。そこで英語でのコミュニケーションを練習します。",
        class_teacher: "LYONS Michael",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611044&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 1,
        class_review: []
      },{
        class_id:34,
        class_faculty: [6011, 6012],
        class_name: "英語初級1-1(コミュニケーション)",
        class_overview: "最も一般的な国際言語である英語について、学生一人ひとりの能力に応じた効果的な学習を通じて4技能（読む・書く・聞く・話す）を向上させるとともに、異文化や社会についての認識を深めることを目標としています。",
        class_teacher: "Smith Hunter Byron",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611045&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 1,
        class_review: ["課題は2週間に1回ぐらいで授業で渡されたプリントをやる。", "たまにスピーチレポートがでる。", "定期テストは授業で使ったプリントを持ち込むことができる。簡単", "ペアワークがある。"]
      },
      {
        class_id:35,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1(リーディング)",
        class_overview: "語彙を増やす・速読をする・読解活動をグループで行った後に討論をしてReadingを通じて理解した内容をDiscussion/Speakingしてクラスメイトと理解を深める。",
        class_teacher: "高野　洋子",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611020&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 2,
        class_review: ["単語の意味とその単語を使った文章を作る課題がでる。", "簡単な英語の本を読む課題もでる。", "定期テストは言われたところを勉強すれば簡単に点がとれる", "1.2回グループで簡単なプレゼンテーションをする。"]
      },
      {
        class_id:36,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1(コミュニケーション)",
        class_overview: "今や国際語となっている英語については、「読む・書く・聴く・話す」の４技能について各自の能力に応じた効果的な学習によりそのスキルの向上を図るとともに、外国の文化や社会に対する認識を深めることを目標とする。",
        class_teacher: "テレサ　カネンバーグ",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611025&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 2,
        class_review: ["課題は、英語で自分の自己紹介をするレポートや英語で好きな場所を紹介するレポートがたまにでる", "講義はテキストを使って行われる", "定期テストは持ち込みなしだが言われたところを少し勉強しておけば大丈夫"]
      },{
        class_id:37,
        class_faculty: [6011, 6012],
        class_name: "英語初級1-1(コミュニケーション)",
        class_overview: "語学力の目的はコミュニケーションです。そこで英語でのコミュニケーションを練習します。",
        class_teacher: "LYONS Michael",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611044&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 2,
        class_review: []
      },
      {
        class_id:38,
        class_faculty: [6011, 6012],
        class_name: "英語初級2-1(コミュニケーション)",
        class_overview: "最も一般的な国際言語である英語について、学生一人ひとりの能力に応じた効果的な学習を通じて4技能（読む・書く・聞く・話す）を向上させるとともに、異文化や社会についての認識を深めることを目標としています。",
        class_teacher: "Smith Hunter Byron",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611045&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 2,
        class_review: ["課題は2週間に1回ぐらいで授業で渡されたプリントをやる。", "たまにスピーチレポートがでる。", "定期テストは授業で使ったプリントを持ち込むことができる。簡単", "ペアワークがある。"]
      },
      {
        class_id:39,
        class_faculty: [6011, 6012],
        class_name: "教養演習",
        class_overview: "ペアワークやグループワーク、レポート課題の作成、グループディスカッション、プレゼンテーションなどの体験を通して、「自分を知る」「社会を知る」「社会と学問との関係を考える」ことを中心に、自分（皆さんひとりひとり）にとって良い人生を送るために「生き方」「働き方」「大学生活の過ごし方」を自分で考え、行動するきっかけをつくる。",
        class_teacher: "新寛　千恵里",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610101&value(crclumcd)=07181",
        class_connection_job: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 3,
        class_review: ["課題は講義中にテーマが発表され講義の終わりにやる。", "席はランダムで3人1グループとなりグループワークを行う。", "定期テストはなくレポートがある。"]
      }, {
        class_id:40,
        class_faculty: [6011, 6012],
        class_name: "コンピュータ演習1(リテラシー)",
        class_overview: "演習を通して、情報リテラシー能力として必要な基礎知識や技能の定着を図る。特に、都市情報に関わる題材を用いながら、学生生活や卒業後の生活に不可欠な情報スキルを習得することを目的とする。",
        class_teacher: "宇野隆　手嶋正章　森龍太",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611129&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 3,
        class_review: ["毎週課題が出るが講義中に終わればなし。", "定期テストは2回ある。", "話を聞かないとわからなくなる。"]
      },
      {
        class_id:41,
        class_faculty: [6011, 6012],
        class_name: "コンピュータ演習1(リテラシー)",
        class_overview: "演習を通して、情報リテラシー能力として必要な基礎知識や技能の定着を図る。特に、都市情報に関わる題材を用いながら、学生生活や卒業後の生活に不可欠な情報スキルを習得することを目的とする。",
        class_teacher: "森杉雅史　柄谷友香　長島正憲",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611130&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 3,
        class_review: ["毎週課題が出るが講義中に終わればなし。", "定期テストは2回ある。", "話を聞かないとわからなくなる。"]
      },
      {
        class_id:42,
        class_faculty: [6011, 6012],
        class_name: "コンピュータ演習1(リテラシー)",
        class_overview: "演習を通して、情報リテラシー能力として必要な基礎知識や技能の定着を図る。特に、都市情報に関わる題材を用いながら、学生生活や卒業後の生活に不可欠な情報スキルを習得することを目的とする。",
        class_teacher: "水野隆文　宮本由紀",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611131&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 3,
        class_review: ["毎週課題が出るが講義中に終わればなし。", "定期テストは2回ある。", "話を聞かないとわからなくなる。"]
      },{
        class_id:43,
        class_faculty: [6011, 6012],
        class_name: "コンピュータ演習1(リテラシー)",
        class_overview: "演習を通して、情報リテラシー能力として必要な基礎知識や技能の定着を図る。特に、都市情報に関わる題材を用いながら、学生生活や卒業後の生活に不可欠な情報スキルを習得することを目的とする。",
        class_teacher: "島田康人　杉浦伸",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611132&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 3,
        class_review: ["毎週課題が出るが講義中に終わればなし。", "定期テストは2回ある。", "話を聞かないとわからなくなる。"]
      },
      {
        class_id:44,
        class_faculty: [6011, 6012],
        class_name: "教養演習",
        class_overview: "ペアワークやグループワーク、レポート課題の作成、グループディスカッション、プレゼンテーションなどの体験を通して、「自分を知る」「社会を知る」「社会と学問との関係を考える」ことを中心に、自分（皆さんひとりひとり）にとって良い人生を送るために「生き方」「働き方」「大学生活の過ごし方」を自分で考え、行動するきっかけをつくる。",
        class_teacher: "新寛　千恵里",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610101&value(crclumcd)=07181",
        class_connection_job: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 4,
        class_review: ["課題は講義中にテーマが発表され講義の終わりにやる。", "席はランダムで3人1グループとなりグループワークを行う。", "定期テストはなくレポートがある。"]
      },
      {
        class_id:45,
        class_faculty: [6011, 6012],
        class_name: "コンピュータ演習1(リテラシー)",
        class_overview: "演習を通して、情報リテラシー能力として必要な基礎知識や技能の定着を図る。特に、都市情報に関わる題材を用いながら、学生生活や卒業後の生活に不可欠な情報スキルを習得することを目的とする。",
        class_teacher: "小池聡　鈴木千文",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611133&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 4,
        class_review: ["毎週課題が出るが講義中に終わればなし。", "定期テストは2回ある。", "話を聞かないとわからなくなる。"]
      },{
        class_id:46,
        class_faculty: [6011, 6012],
        class_name: "コンピュータ演習1(リテラシー)",
        class_overview: "演習を通して、情報リテラシー能力として必要な基礎知識や技能の定着を図る。特に、都市情報に関わる題材を用いながら、学生生活や卒業後の生活に不可欠な情報スキルを習得することを目的とする。",
        class_teacher: "亀井栄治　大野沙知子",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611135&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 4,
        class_review: ["毎週課題が出るが講義中に終わればなし。", "定期テストは2回ある。", "話を聞かないとわからなくなる。"]
      },
      {
        class_id:47,
        class_faculty: [6011, 6012],
        class_name: "コンピュータ演習1(リテラシー)",
        class_overview: "演習を通して、情報リテラシー能力として必要な基礎知識や技能の定着を図る。特に、都市情報に関わる題材を用いながら、学生生活や卒業後の生活に不可欠な情報スキルを習得することを目的とする。",
        class_teacher: "杉浦伸　長島正章",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611134&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 4,
        class_review: ["毎週課題が出るが講義中に終わればなし。", "定期テストは2回ある。", "話を聞かないとわからなくなる。"]
      },
      {
        class_id:48,
        class_faculty: [6011, 6012],
        class_name: "コンピュータ演習1(リテラシー)",
        class_overview: "演習を通して、情報リテラシー能力として必要な基礎知識や技能の定着を図る。特に、都市情報に関わる題材を用いながら、学生生活や卒業後の生活に不可欠な情報スキルを習得することを目的とする。",
        class_teacher: "森龍太　小林翔",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611129&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 4,
        class_review: ["毎週課題が出るが講義中に終わればなし。", "定期テストは2回ある。", "話を聞かないとわからなくなる。"]
      },{
        class_id:49,
        class_faculty: [6011, 6012],
        class_name: "宗教の世界",
        class_overview: "世界の主な宗教（キリスト教・イスラム教・仏教）を概観し、それぞれがどのような世界観を持ち、どのような思想を持っているのかを解説する。",
        class_teacher: "井上　研",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610008&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 3,
        class_time: 5,
        class_review: ["１万字以内のレポートが最後にある。"]
      },
      {
        class_id:50,
        class_faculty: [6011, 6012],
        class_name: "現象と論理",
        class_overview: "身の回りの自然現象を取り上げ、それを理解するために必要な科学の基礎理論を学ぶとともに、論理的な思考方法を習得し、自ら真理を発見する能力を養成することを目的としている。",
        class_teacher: "張　昇平",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610018&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 1,
        class_review: ["レポートが5回ぐらいでる(A4用紙3枚ぐらい)", "毎週の課題はない", "レポートさえ出しておけば単位はとれる。", "教科書はない"]
      },
      {
        class_id:51,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1(コミュニケーション)",
        class_overview: "今や国際語となっている英語については、「読む・書く・聴く・話す」の４技能について各自の能力に応じた効果的な学習によりそのスキルの向上を図るとともに、外国の文化や社会に対する認識を深めることを目標とする。",
        class_teacher: "テレサ　カネンバーグ",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611025&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 2,
        class_review: ["課題は、英語で自分の自己紹介をするレポートや英語で好きな場所を紹介するレポートがたまにでる", "講義はテキストを使って行われる", "定期テストは持ち込みなしだが言われたところを少し勉強しておけば大丈夫"]
      },{
        class_id:52,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1（リーディング）",
        class_overview: "日本を含む先進国に共通または類似の、論争になりがちなテーマに関して賛成・反対それぞれの意見を述べた英文エッセイを読むことを通じて、英文読解力および基本的な意見構成力を身につけることを目的とする",
        class_teacher: "橋本　久美子",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611022&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 2,
        class_review: [],
      },
      {
        class_id:53,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1（リーディング）",
        class_overview: "英語の学習を単なる言葉の学習にとどめず、身近で興味深いさまざまなトピックを取り上げ、読む・書く・話す・聞くの４技能をバランスよく伸ばすとともに、読解力の向上を図りながら、現代社会の最新事情についての理解を深めることを目的とする",
        class_teacher: "葛谷　明美",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611041&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 2,
        class_review: ["小テストが毎回ある(範囲の教科書を勉強しておけば大丈夫)"],
      },
      {
        class_id:54,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1（リーディング）",
        class_overview: "今や国際語となっている英語については、「読む・書く・聴く・話す」の４技能について各自の能力に応じた効果的な学習によりそのスキルの向上を図るとともに、外国の文化や社会に対する認識を深めることを目標とする。",
        class_teacher: "古田　雪子",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611040&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 2,
        class_review: ["テストが単語テストと文章題。単語はテキストと一緒。文章題は初見。", "講義が終わるのが少し早い。"],
      },{
        class_id:55,
        class_faculty: [6011, 6012],
        class_name: "人間と環境",
        class_overview: "本講義は特に地球温暖化問題において重点を置く。 温暖化についてはその起因を二酸化炭素排出とする主流派説、及びそれを非とする懐疑派説、いずれについても立場を固定しないで解説する。両者の考え方と相違をくみ取ることで、これからの日本の温暖化対策について合理的な思考を形成する。",
        class_teacher: "森杉　雅史",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610019&value(crclumcd)=07181",
        class_connection_job: [11],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 2,
        class_review: ["毎週ミニレポートが課題ででる。", "定期テストはほとんど過去問と同じ。資料が２つある。"],
      },
      {
        class_id:56,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1(コミュニケーション)",
        class_overview: "今や国際語となっている英語については、「読む・書く・聴く・話す」の４技能について各自の能力に応じた効果的な学習によりそのスキルの向上を図るとともに、外国の文化や社会に対する認識を深めることを目標とする。",
        class_teacher: "テレサ　カネンバーグ",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611025&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 3,
        class_review: ["課題は、英語で自分の自己紹介をするレポートや英語で好きな場所を紹介するレポートがたまにでる", "講義はテキストを使って行われる", "定期テストは持ち込みなしだが言われたところを少し勉強しておけば大丈夫"],
      },
      {
        class_id:57,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1（リーディング）",
        class_overview: "日本を含む先進国に共通または類似の、論争になりがちなテーマに関して賛成・反対それぞれの意見を述べた英文エッセイを読むことを通じて、英文読解力および基本的な意見構成力を身につけることを目的とする",
        class_teacher: "橋本　久美子",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611022&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 3,
        class_review: [],
      },{
        class_id:58,
        class_faculty: [6011, 6012],
        class_name: "英語基礎1（リーディング）",
        class_overview: "今や国際語となっている英語については、「読む・書く・聴く・話す」の４技能について各自の能力に応じた効果的な学習によりそのスキルの向上を図るとともに、外国の文化や社会に対する認識を深めることを目標とする。",
        class_teacher: "古田　雪子",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611040&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 3,
        class_review: ["テストが単語テストと文章題。単語はテキストと一緒。文章題は初見。", "講義が終わるのが少し早い。"],
      },
      {
        class_id:59,
        class_faculty: [6011, 6012],
        class_name: "英語初級2－1（リーディング）",
        class_overview: "英語の学習を単なる言葉の学習にとどめず、身近で興味深いさまざまなトピックを取り上げ、読む・書く・話す・聞くの４技能をバランスよく伸ばすとともに、読解力の向上を図りながら、現代社会の最新事情についての理解を深めることを目的とする。",
        class_teacher: "葛谷　明美",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611049&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 3,
        class_review: ["小テストが毎回ある(範囲の教科書を勉強しておけば大丈夫)"],
      },
      {
        class_id:60,
        class_faculty: [6011, 6012],
        class_name: "情報とビジネス",
        class_overview: "ビジネスにおける情報活用および経営戦略の概要を把握し、企業が必要とするデータおよびその取得方法、目的に添った情報を導き出す解析法やデータマイニングを学ぶとともに、企業が目ざすサービスサイエンスに関する応用技術を創造する。",
        class_teacher: "岸　博之",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610165&value(crclumcd)=07181",
        class_connection_job: [1, 7, 10, 11],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 4,
        class_time: 5,
        class_review: ["レポートが何回かある。", "教科書が必要", "レポートをしっかり書いておけば単位はとれる。"],
      },{
        class_id:61,
        class_faculty: [6011, 6012],
        class_name: "歴史の文化",
        class_overview: "現代に至るまでの長い歴史の中で、私たちはさまざまな歴史・文化を蓄積してきました。この授業では、文化現象としての災害・危機・セキュリティという観点から、とくに日本近代の歴史過程を、具体的な事例を挙げながら考える。",
        class_teacher: "姜　海守",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610001&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 5,
        class_time: 1,
        class_review: ["レポートが3回ぐらいある。", "講義の最後に感想を紙に書いて提出する", "プリントをなくさずもっておく(レポートで使う)", "定期テストはない"],
      },
      {
        class_id:62,
        class_faculty: [6011, 6012],
        class_name: "コンピュータリテラシー",
        class_overview: "情報技術を扱う人材として、必要な基本的知識の習得を目指す。本講義では、基本情報処理技術者試験の試験範囲のうちテクノロジ系分野の知識を中心に解説する。",
        class_teacher: "水野　隆文",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610076&value(crclumcd)=07181",
        class_connection_job: [1, 11],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 5,
        class_time: 1,
        class_review: ["講義をしっかり聞いておかないと分からなくなる。", "復習もしっかりしといた方がいい", "定期テストは毎週の講義最後にもらえるプリントを中心に勉強する。", "先生が優しく最低限やっていれば単位をくれる"],
      },
      {
        class_id:63,
        class_faculty: [6011, 6012],
        class_name: "哲学",
        class_overview: "心って何？機械は心を持てるの？わたしはなぜわたしなの？講義ではこれらの疑問について現代まで続いている議論について学習する。",
        class_teacher: "井上　研",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610006&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 5,
        class_time: 2,
        class_review: ["めっちゃ楽", "定期テストなし", "出席してミニレポートを出せばいける"],
      },{
        class_id:64,
        class_faculty: [6011, 6012],
        class_name: "文化人類学の世界",
        class_overview: "よりよい異文化との共存・交流の形成を目指し、自文化を相対化する視点を養うことを目的としている。",
        class_teacher: "姜　海守",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610005&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 5,
        class_time: 2,
        class_review: [],
      },
      {
        class_id:65,
        class_faculty: [6011, 6012],
        class_name: "都市と人間",
        class_overview: "さまざまなセクターや職業からまちづくりに関わる人の「職能（思い・志／きっかけ・経緯／知識・スキルなど）」を学びます。テキストによる講義とゲストトークを通して、自分自身の学部４年間の学びや将来像について考えていく。",
        class_teacher: "田口　純子",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610014&value(crclumcd)=07181",
        class_connection_job: [1, 2, 4, 5, 6, 7, 8, 9, 11],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 5,
        class_time: 3,
        class_review: ["2回に1回ゲストが来て話をしてくれる。", "定期テストはなくレポートがある。", "近くの人とペアワークをする時がある。", "単位は取りやすい"],
      },
      {
        class_id:66,
        class_faculty: [6011, 6012],
        class_name: "都市情報学概論1",
        class_overview: "講義内容は多岐にわたるが，各担当者は，下記の｢授業の要旨｣で示されているように，現在取り組んでいる研究テーマの内容をできるだけ分かり易く説明し，また，授業の終わりに毎回学生諸君から質問を受け，それに答える形で学生諸君の都市問題に対する関心をできるだけ引き出すように努める。",
        class_teacher: "亀井　栄治",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=611103&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 1,
        class_grade: 1,
        class_semester: 1,
        class_dow: 5,
        class_time: 4,
        class_review: ["毎週教授が違う。", "週によって課題の重さが違う。", "毎週の課題をしっかりやっておけば単位はとれる。"],
      },{
        class_id:67,
        class_faculty: [6011, 6012],
        class_name: "法と社会",
        class_overview: "学士として必要とされる学識の一つとして、法的知識と法的思考力の涵養を目的とする。",
        class_teacher: "細川　壮平",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610010&value(crclumcd)=07181",
        class_connection_job: [],
        class_type: 3,
        class_grade: 1,
        class_semester: 1,
        class_dow: 5,
        class_time: 5,
        class_review: ["憲法について学ぶ。", "深いところまではやらない。", "出席は〇を講義中に付けなければならない。", "定期テストは持ち込みあり。"],
      },
      {
        class_id:68,
        class_faculty: [6011, 6012],
        class_name: "数学の基礎B-1",
        class_overview: "線形代数の基礎的な概念および手法を講義と演習を通して学習する．",
        class_teacher: "鈴木　淳生",
        class_url: "https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssbdr.do?value(risyunen)=2023&value(semekikn)=1&value(kougicd)=610169&value(crclumcd)=07181",
        class_connection_job: [1, 7, 11],
        class_type: 2,
        class_grade: 1,
        class_semester: 1,
        class_dow: 5,
        class_time: 5,
        class_review: ["課題なし", "講義終わりに確認問題。"],
      }
  ]);

  return (
    <FacultyInfoContext.Provider value={{ classInfo, setClassInfo }}>
      {children}
    </FacultyInfoContext.Provider>
  );
};